[workspace]
resolver = "3"
members = [
    "crates/cli",
    "crates/core",
    "crates/codegen",
    "crates/ast",
    "crates/parser", "crates/inference",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
