[package]
name = "elk-core"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
nom = "7.1.3"
cranelift = "0.117.0"
cranelift-native = "0.117.0"
cranelift-object = "0.117.2"
cranelift-module = "0.117.2"
