[package]
name = "elk-core"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
nom = "8.0.0"
cranelift = "0.118.0"
cranelift-native = "0.118.0"
cranelift-object = "0.118.0"
cranelift-module = "0.118.0"
