[package]
name = "elk"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
elk-core = { path = "../compiler-core" }
clap = { version = "4.5.16", features = ["derive"] }
anyhow = "1.0.89"
