[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { path = "../ast" }
cranelift = "0.118.0"
cranelift-native = "0.118.0"
cranelift-object = "0.118.0"
cranelift-module = "0.118.0"
